app/dmplotter/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import SubmitField, SelectMultipleField, FileField, DecimalField, RadioField, FloatField, SelectField
from wtforms import validators


class DatasetForm(FlaskForm):
    select = SubmitField('Plot Data')
    gSM_input = FloatField('gSM_input')
    conditional_input = RadioField(u'Data Type', choices=[(u'SD', 'Spin-Dependent'), (u'SI', 'Spin-Independent')], validators=[validators.Optional()])
    radio_inputSI = RadioField(u'Spin-Independent', choices=[('scalar', 'Scalar'), ('vector', 'Vector')], default='scalar',validators=[validators.Optional()])
    datasets = SelectMultipleField('datasets', choices=[], validators=[validators.DataRequired()])
    savedPlots = SelectField('datasets', choices=[], validators=[validators.Optional()])
    #gSM_input = FloatField('gSM_input')
    #conditional_input = RadioField(u'Conditional Type', choices=[('SD', 'Spin-Dependent'), ('SI', 'Spin-Independent')])

class UploadForm(FlaskForm):
    data_file = FileField('dataset', validators=[
        FileRequired(),
        FileAllowed(['xml'], 'datasets only!')
    ])
    upload_button = SubmitField('Upload Dataset')

class Set_gSM_Form(FlaskForm):
    #gSM_input = FloatField('gSM_input')
    gD_input = FloatField('gD_input')
    gU_input = FloatField('gU_input')
    gS_input = FloatField('gS_input')
    set_button = SubmitField('Refresh Plot')

app/dmplotter/__init__.py
# __init__.py is a special Python file that allows a directory to become
# a Python package so it can be accessed using the 'import' statement.

app/views/main_views.py
# -*- coding: utf-8 -*-
import os
from flask import Blueprint, redirect, render_template, request, url_for, flash
from flask_user import current_user, login_required, roles_required

from app import app, db, getUserPath
from app.models.user_models import UserProfileForm

#DM Limiter
from itertools import cycle
from flask import Flask, render_template, request, redirect, url_for, session, json, make_response
from werkzeug.utils import secure_filename
from werkzeug.datastructures import CombinedMultiDict
from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.embed import components
from bokeh.models import LinearAxis, Label, Legend
import bokeh
import pandas as pd
from flask import send_from_directory
import numpy as np
#import pdfkit
#DM Packages
from app.dmplotter.plotter import get_data, get_datasets, get_metadata, set_SI_modifier, get_SI_modifier, getSimplifiedPlot, getDDPlot, getLegendPlot, validateFile
from app.dmplotter.forms import DatasetForm, UploadForm, Set_gSM_Form
from app.dmplotter.conversion import set_gSM, get_gSM
#DM Default
ALLOWED_EXTENSIONS = set(['xml'])
selected_datasets = []
colors = cycle(['red', 'blue', 'green', 'orange'])

def determine(data):
    if data is None:
        return False;
    else:
        return True;

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def getSavedPlots():
    globalPlots = json.load(open("savedPlots.json"))
    userPlots  = {}
    if(os.path.isfile('data/'+getUserPath()+'/userPlots.json')):
        userPlots = json.load(open('data/'+getUserPath()+'/userPlots.json'))
    allPlots = {key: value for (key, value) in ({"":""}.items() + globalPlots.items() + userPlots.items())}
    return allPlots
#End DM

main_blueprint = Blueprint('main', __name__, template_folder='templates')

# The Home page is accessible to anyone
@main_blueprint.route('/')
def home_page():
    return render_template('main/home_page.html')


# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/member')
@login_required  # Limits access to authenticated users
def member_page():
    return render_template('main/user_page.html')


# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_required('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('main/admin_page.html')


@main_blueprint.route('/main/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.home_page'))

    # Process GET or invalid POST
    return render_template('main/user_profile_page.html',
                           form=form)

@main_blueprint.route('/about')
def about_page():
    return render_template('about.html')

@main_blueprint.route('/theory')
def theory_page():
    return render_template('theory.html')

@main_blueprint.route('/dmplotter', methods=['GET', 'POST'])
@login_required
def dmplotter():
    known_datasets = get_datasets()
    gu, gd, gs = get_gSM()
    si_modifier = get_SI_modifier()

    #Generate Array of options
    options = list(getSavedPlots().keys())

    dataset_selection = DatasetForm(gSM_input=gu)
    dataset_selection.datasets.choices = zip(get_datasets(), get_datasets())
    dataset_selection.savedPlots.choices = zip(options, options)
    dataset_upload = UploadForm()

    global selected_datasets
    print(selected_datasets)

    if request.method == 'POST':
        # check if the post request has the file part
        # print(request.values, request.data, request.form)
        print(dataset_selection.datasets.data)
        if dataset_selection.validate():
            selected_datasets = dataset_selection.datasets.data
            gSM = dataset_selection.gSM_input.data
            set_gSM(gSM,gSM,gSM)
            gu, gd, gs = get_gSM()
            si_modifier = dataset_selection.radio_inputSI.data
            set_SI_modifier(si_modifier)

    datasets = selected_datasets
    dfs = map(get_data, datasets)

    #Filter, TODO: Apply filter to selected_datasets prior to conversion (attempt)
    #get_data will return a 'None' object if the selected dataset could not be converted, (bad experiement string..)
    dfs = [x for x in dfs if determine(x)]

    metadata = map(get_metadata, datasets)
    allmetadata = map (get_metadata,known_datasets)

    p1 = getSimplifiedPlot()
    p2 = getDDPlot()
    legendPlot = getLegendPlot()

    legendItems = []
    x = 1
    y = 2*x
    for df, color in zip(dfs, colors):
        label = df['label'].any()
        df['color'] = color
        p1.line(df['m_med'], df['m_DM'], line_width=2, color=color)
        p2.line(df['m_DM'], df['sigma'], line_width=2, color=color)
        line = legendPlot.line(x,y,line_width=2, color=color)
        legendItems.append((label,[line]))

    #Initialize all_data in the case that all datasets selected where invalid
    all_data = pd.DataFrame()
    if(len(dfs) > 0):
        all_data = pd.concat(dfs)

    legend = Legend(items=legendItems, location=(0, 0))
    legendPlot.add_layout(legend, 'above')

    script1, div1 = components(p1, CDN)
    script2, div2 = components(p2, CDN)
    script3, div3 = components(legendPlot,CDN)
    return render_template('dmplotter.html',
                           plot_script1=script1, plot_div1=div1,
                           plot_script2=script2, plot_div2=div2,
                           plot_script3=script3, plot_div3=div3,
                           bokeh_version=bokeh.__version__,
                           data_table=all_data.to_html(),
                           datasets = known_datasets,
                           metadata = metadata,
                           dataset_selection = dataset_selection,
                           selected_datasets = selected_datasets,
                           allmetadata = allmetadata,
                           savedPlots = getSavedPlots(),
                           dataset_upload = dataset_upload,
                           si_modifier = si_modifier,
                           gSM_gSM=gu,
                           gSM_gU=gu,gSM_gD=gd,gSM_gS=gs)

@main_blueprint.route('/updateValues', methods=['GET', 'POST'])
def updateValues():
    gSM_refresh = Set_gSM_Form()
    gSM = gSM_refresh.gSM_input.data
    set_gSM(gSM,gSM,gSM)
    #Future: Individually set coupling constant
    #gU = gSM_refresh.gU_input.data
    #gD = gSM_refresh.gD_input.data
    #gS = gSM_refresh.gS_input.data
    #set_gSM(gU,gD,gS)
    return redirect(url_for('main.dmplotter'))

@main_blueprint.route('/savePlot', methods=['GET', 'POST'])
def savePlot():
    savedPlotName = request.form['name']
    selected_datasets = request.form['data'].split(",")
    userPlots = {}
    #Create the User directory if not exists- TODO: do at time of account setup
    directory = 'data/'+getUserPath()
    if not os.path.exists(directory):
        os.makedirs(directory)
    if(os.path.isfile(directory+'/userPlots.json')):
        userPlots = json.load(open('data/'+getUserPath()+'/userPlots.json'))
    userPlots[savedPlotName] = selected_datasets

    with open('data/'+getUserPath()+'/userPlots.json', 'w') as f:
        json.dump(userPlots, f)
    return redirect(url_for('main.dmplotter'))

@main_blueprint.route('/pdf', methods=['GET', 'POST'])
def generatePDF():

    gu, gd, gs = get_gSM()
    si_modifier = get_SI_modifier()

    global selected_datasets
    #Will re-use the previously selected values for the dataset_type
    #Optional: provide datasel file names in the POST parameters
    if request.method == 'POST':
        print('Use this are to parse to posted datasets');

    datasets = selected_datasets
    dfs = map(get_data, datasets)

    #Filter, TODO: Apply filter to selected_datasets prior to conversion (attempt)
    #get_data will return a 'None' object if the selected dataset could not be converted, (bad experiement string..)
    dfs = [x for x in dfs if determine(x)]

    metadata = map(get_metadata, datasets)

    p1 = getSimplifiedPlot()
    p2 = getDDPlot()
    legendPlot = getLegendPlot()

    legendItems = []
    x = 1
    y = 2*x
    for df, color in zip(dfs, colors):
        label = df['label'].any()
        df['color'] = color
        p1.line(df['m_med'], df['m_DM'], line_width=2, color=color)
        p2.line(df['m_DM'], df['sigma'], line_width=2, color=color)
        line = legendPlot.line(x,y,line_width=2, color=color)
        legendItems.append((label,[line]))

    #Initialize all_data in the case that all datasets selected where invalid
    all_data = pd.DataFrame()
    if(len(dfs) > 0):
        all_data = pd.concat(dfs)

    legend = Legend(items=legendItems, location=(0, 0))
    legendPlot.add_layout(legend, 'above')

    script1, div1 = components(p1, CDN)
    script2, div2 = components(p2, CDN)
    script3, div3 = components(legendPlot,CDN)
    html =  render_template('pdf.html',
                           plot_script1=script1, plot_div1=div1,
                           plot_script2=script2, plot_div2=div2,
                           plot_script3=script3, plot_div3=div3,
                           bokeh_version=bokeh.__version__,
                           metadata = metadata,
                           selected_datasets = selected_datasets,
                           si_modifier = si_modifier,
                           gSM_gSM=gu)
    return html
'''
    css = 'app/static/css/style.css'
    pdf = pdfkit.from_string(html, False, css=css)

    response = make_response(pdf)
    response.headers['Content-Type'] = 'application/pdf'

app/templates/about.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}

<div class="row" style="margin-top:5%;">
 <div class="col justify-content-center" style="text-align:left">

   <h1>About</h1>
   <span>This app was developed at Brandeis University to leverage research by Bjoern Penning in the search for Dark Matter. The app leverages a conversion algorithm to compare results between various collider experiments and direct detection experiments. DM Limiter will analyze the selected results and  plot both the simplified model plane and the direct detection plane for comparison.
   </span>



 </div>
</div>

{% endblock %}

app/templates/dmplotter.html
{% extends "layout.html" %}  {# main/main_base.html extends layout.html #}

{% block extra_css %}
<link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.14.min.css" type="text/css" />
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.14.min.js"></script>
<script type="text/javascript">
		//Collect all the flask variables for use in the main js script
		var selected_datasets_js = {{selected_datasets|tojson}};
		var metadata = [];
		{% for data in allmetadata  %}
		metadata.push({{data|tojson}});
		{% endfor %}
		var plots = {{savedPlots|tojson}};
		var csrf = '{{ csrf_token() | safe }}';
</script>
<script src="{{ url_for('static', filename='scripts/main.js') }}"></script>

	<!-- plot  scripts-->
	{% if plot_script1 %}
		{{ plot_script1 | safe}}
	{% endif %}
	{% if plot_script2 %}
		{{ plot_script2 | safe}}
	{% endif %}
	{% if plot_script3 %}
		{{ plot_script3 | safe}}
	{% endif %}

{% endblock %}


{% block content %}


	 <div class="row justify-content-start" style="margin-top:5%;">
  	<div class="col justify-content-start">
  		<h3>How this app works</h3>
  		<ul>
  			<li>Select two or more limit samples</li>
  			<li>Create comparison plot</li>
  			<li>Download PDF for publications.</li>
  			<li>Use XXX to cite us</li>
  		</ul>
  	</div>
		<div class="col justify-content-end">
			<h3>Upload new dataset</h3>
			<form method="POST" action="/upload" enctype="multipart/form-data">
				{{ dataset_upload.hidden_tag() }}
				{{ dataset_upload.data_file(class="btn btn-default") }}
			<div style='text-align:right;'>
				{{ dataset_upload.upload_button(class="btn btn-outline-primary") }}
			</div>
			</form>
		</div>
	</div>

<div class="headerTitle">
	Dataset Selection
</div>

<div class="datainput">
	<form method="POST" action="/dmplotter" name="dataset_selection">
  	<div class="row justify-content-start">
			<div class="col">
				<h3>Select datasets to plot:</h3>
					{{ dataset_selection.hidden_tag() }}
					{{ dataset_selection.datasets(class="selectpicker",**{"onchange":"displayMetadata(this)"}) }}
			</div>

		<div class="col justify-content-end">
			<h3>Conditionally Select Datasets:</h3>
				{{dataset_selection.conditional_input(**{"onchange":"updateConditionalSelect(this)"}) }}
				<h3>Saved Plots:</h3>
				{{ dataset_selection.hidden_tag() }}
				{{ dataset_selection.savedPlots(class="selectpicker",**{"onchange":"selectPlots(this)"}) }}
		</div>

	</div>
	<hr>
	<div class="row justify-content-start">
		<div class="col">
			<div style="display:block;">
			<h3>Filter Datasets</h3>

			<select multiple class='filterBox' onchange="updateFilter(this,'experiment')" >
					<option>CMS</option>
					<option>DarkSide</option>
					<option>IceCube</option>
					<option>LHC</option>
					<option>LUX</option>
					<option>PandaX</option>
					<option>PICO</option>
					<option>SuperCDMS</option>
					<option>XENON100</option>
					<option>XENON1T</option>
			</select>

			<select multiple class='filterBox' onchange="updateFilter(this,'spinDependency')" >
					<option>SD</option>
					<option>SI</option>
			</select>

			<select multiple class='filterBox' onchange="updateFilter(this,'year')">
					<option>2018</option>					
					<option>2017</option>
					<option>2016</option>
		 	</select>


			</div>
		</div>
	</div>

	<div class="row justify-content-start">
		<div class="col" id='filterDatasets'>
			<!-- Metadata from the filtered datasets will be displayed here. -->
		</div>
	</div>
	<hr>

<div class="row justify-content-start" style="margin-top:10px;">
	<div class="col">
		<h3>Standard Model coupling constant:</h3>
				gSM = {{ dataset_selection.gSM_input}}<br>
		<h3>Spin-Independent Model</h3>
				{{dataset_selection.radio_inputSI}}
	</div>
	<div class="col" style='text-align:right;'>
		<div id="parent">
			<div id="child">

				{{ dataset_selection.select(class="btn btn-outline-primary") }}
			</div></div>
	</div>
</div>
</form>

	<hr>

	<div class="row justify-content-start">
		<div class="col justify-content-start">
			<h3>Dataset Info</h3>
				<div id='datasetInfo'>
				</div>
		</div>
		<div class="col" style='text-align:right;'>
			<div id="parent">
				<div id="child">

				<a id="clearSelection" href="#" class="btn btn-outline-primary plotBtn">Clear All</a>
			</div></div>
		</div>
  	</div>
	

</div>

<!-- -->

<div class="headerTitle">
	Comparison Plot
</div>

<div class="datainput">
			<div class="row">
				<div class="col justify-content-right">
					{% if plot_div1 is defined %}
						{{ plot_div1 | safe }}
					{% endif %}
				</div>
				<div class="col justify-content-left">
					{% if plot_div2 is defined %}
						{{ plot_div2 | safe }}
					{% endif %}
				</div>
			</div>

			<div class="row">
				<div class="col justify-content-left">
					{% if plot_div3 is defined %}
						{{ plot_div3 | safe }}
					{% endif %}
				</div>
				<div class="col">
					<input type="text" id="plotName" name="plotName" placeholder="Plot Name"><br>
					<a id="savePlots" href="#" class="btn btn-outline-primary plotBtn">Save Plots</a>
					<hr>
					<a id="showData" href="#" class="btn btn-outline-primary plotBtn">Show Data</a>
					<a id="downloadPDF" href="pdf.html" class="btn btn-outline-primary plotBtn">Download PDF</a>
				</div>
			</div>
			<hr>
	<div class="row justify-content-start" style="margin-top:5%;">
		<div class="col">
			<h3>Selected Datasets:</h3>
			{% for data in metadata  %}
			<div class='row'>
				<div class='col col-3' style='font-weight:bold'>Filename:</div>
				<div class='col'>{{data['fileName']}}</div>
			</div>
			<div class='row'>
				<div class='col col-3' style='font-weight:bold'>Label:</div>
				<div class='col'>{{data['dataLabel']}}</div>
			</div>
			<div class='row'>
				<div class='col col-3' style='font-weight:bold'>Comment:</div>
				<div class='col'>{{data['dataComment']}}</div>
			</div>
			<div class='row'>
				<div class='col col-3' style='font-weight:bold'>Reference:</div>
				<div class='col'>{{data['dataReference'] | safe}}</div>
			</div>
			<div class='row'>
				<div class='col col-3' style='font-weight:bold'>Experiment:</div>
				<div class='col'>{{data['experiment']}}</div>
			</div>
			<div class='row'>
				<div class='col col-3' style='font-weight:bold'>Spin:</div>
				<div class='col'>{{data['spinDependency']}}</div>
			</div>
			<hr>
			{% endfor %}
		</div>
		<div class="col justify-content-end">
			<h3>Selected Standard Model coupling constant:</h3>
			<p>	gSM= {{gSM_gSM}}<br>
			</p>
			<h3>Spin-Independent Model</h3>
			<p>	{{si_modifier}}<br>
			</p>
		</div>
	</div>
</div>

<hr>

		<div class="row justify-content-center" style="margin-top:5%;">
  		<div class="col" id="dataDiv">
  			{% if data_table is defined %}
  				<h3>The data</h3>
  				{{ data_table | safe }}
  			{% endif %}
  		</div>
		</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- These 3 meta tags MUST come first -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- These 3 meta tags MUST come first -->
        <title>{{ user_manager.USER_APP_NAME }}</title>

        <!-- Bootstrap CSS and JS -->
        <!-- <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet"> -->
        <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">


        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="{{ url_for('static', filename='bootstrap/js/html5shiv.min.js') }}"></script>
            <script src="{{ url_for('static', filename='bootstrap/js/respond.min.js') }}"></script>
        <![endif]-->

        <!-- In-lining styles to avoid needing a separate .css file -->
        <style>
            hr { border-color: #cccccc; margin: 0; }
            .no-margins { margin: 0px; }
            .with-margins { margin: 10px; }
            .col-centered { float: none; margin: 0 auto; }
        </style>

        <!-- Application specific CSS-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">

        {# *** Allow sub-templates to insert extra html to the head section *** #}
        {% block extra_css %}{% endblock %}
        {% block extra_js %}{% endblock %}
    </head>
    <body>
        {% block body %}
        <!-- Application specific HTML -->
        <nav class="navbar navbar-expand-md bg-primary navbar-dark" style="text-align:right">
          <div class="container">
            <div class="row" style="width:100%;">
            <div class="col justify-content-start" style="text-align: left;">
              <a class="btn btn-outline-primary text-white" href="http://www.brandeis.edu/departments/physics/">Brandeis University - Center for the Dark Universe</a>
            </div>
              <div class="col justify-content-end" >
                <a href="{{ url_for('main.theory_page') }}" class="btn btn-outline-primary text-white">Theory</a>
                <a href="{{ url_for('main.about_page') }}" class="btn btn-outline-primary text-white">About</a>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('user.logout') }}" class="btn btn-outline-primary text-white">Sign out</a>
                {% else %}
                <a href="{{ url_for('user.login') }}" class="btn btn-outline-primary text-white">Sign in</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
        <div class="container">
          <div class="row">
            <div class="col-md-12" >
              <div id="dmTitle">
                DM Limiter
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12" >
              <p class="subTitle">Dark matter limit comparisons using simplified models</p>
            </div>
          </div>
        </div>

      <!--
        <div id="header-div" class="clearfix with-margins">
            <div class="pull-left"><a href="/"><h1 class="no-margins">Flask-User starter app</h1></a></div>
            <div class="pull-right">
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('main.user_profile_page') }}">{{ current_user.first_name or current_user.username or current_user.email }}</a>
                    &nbsp; | &nbsp;
                    <a href="{{ url_for('user.logout') }}">Sign out</a>
                {% else %}
                    <a href="{{ url_for('user.login') }}">Sign in</a>
                {% endif %}
            </div>
        </div>
      -->
        <hr class="no-margins"/>

        <div id="main-div" class="with-margins">
        {% block pre_content %}{% endblock %}

        {# One-time system messages called Flash messages #}
        {% block flash_messages %}
            {%- with messages = get_flashed_messages(with_categories=true) -%}
                {% if messages %}
                    {% for category, message in messages %}
                        {% if category=='error' %}
                            {% set category='danger' %}
                        {% endif %}
                        <div class="alert alert-{{category}}">{{ message|safe }}
                          <button type="button" class="close" data-dismiss="alert">&times;</button>
                        </div>
                    {% endfor %}
                {% endif %}
            {%- endwith %}
        {% endblock %}

        {% block main %}
        <div class="container">
            <div class="row">
                <div class="col-centered">
            {% block content %}{% endblock %}
                </div>
              </div>
            </div>
        {% endblock %}
        </div>

        <br/>
        <hr class="no-margins"/>

        <div class="container" id='dm_footer'>
          <div class="row" style="width:100%;">
            <div class="col justify-content-start" style="text-align: left;">{{ user_manager.USER_APP_NAME }} v1.4 </div>
            <div class="col justify-content-start" style="text-align: center;">Use XXX to cite.</div>
            <div class="col justify-content-end" style="text-align: right;"> &copy; 2018 Brandeis University</div>
          </div>
        </div>

        <!-- Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>


        <!-- Optional Google Analytics: change UA-XXXXX-X to be your site's ID.
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        -->
        {% endblock %}
    </body>
</html>

app/templates/theory.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}
<div class="row" style="margin-top:5%;">
 <div class="col justify-content-center" style="text-align:left">

   <h1>Theory</h1>
   <span>We know that about 27% of our Universe's energy content is composed of an unknown form of matter - dark matter (DM) - that is entirely different from the normal matter which contributes just about 5%.  The evidence for DM is strong and consistent across all scales from the galactic to the cosmological. DM has not yet been directly observed and it will be one of the most important discoveries in fundamental physics. However, all current evidence for DM is purely of gravitational nature. Why then should we use colliders, in particular hadron colliders where particles are mainly produced via the strong force, to search for DM?
   </span>



 </div>
</div>
{% endblock %}